### ISSUE TITLE
Clear Inputs

### ISSUE THREAD

**Issue by Tobiaspk** [hussenmi/hto_dnd#1]
Current dsb function requires a `raw` and `filtered` inputs. It can be misleading what this function does. Propose to name inputs:

* `adata_filtered`
* `adata_background`

Also, propose to add a test if any barcodes overlap. If there is an overlap, remove the overlap from background and inform the user about this.

**Comment by hussenmi** [comment]
Here, we're not taking the background data, though. We're taking in the raw data and getting the background ourselves. This is because, usually the data that people will have is the filtered and raw values; asking them to provide the background would require them to do some data manipulation themselves, which we are already doing here.
As for the overlapping barcodes, because we are expecting raw data, there should be overlapping barcodes (which would be the filtered data)
